const GETTING_SONGS = 'GETTING_SONGS'
const GETTING_CURRENT_SONG = 'GETTING_CURRENT_SONG'
const PUT_NEW_SONGS = 'PUT_NEW_SONGS'
const PUT_NEW_CURRENT_SONG = 'PUT_NEW_CURRENT_SONG'
const SORT_SONGS = 'SORT_SONGS'
const FORMAT_ACTIVE_FAVORITES = 'FORMAT_ACTIVE_FAVORITES'


export {
    GETTING_SONGS, 
    GETTING_CURRENT_SONG,
    PUT_NEW_SONGS,
    PUT_NEW_CURRENT_SONG,
    SORT_SONGS,
    FORMAT_ACTIVE_FAVORITES,
}

